name: wharehouse
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  math_expressions: ^3.1.0
  http: ^1.6.0
  path: any
  excel: any
  googleapis: any
  googleapis_auth: any
  sqflite_common_ffi: any
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
